# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Afficher les infos de l'événement
        run: |
          echo "Commit : ${{ github.sha }}"
          echo "Auteur : ${{ github.actor }}"
